spring.application.name=demo


server.port=8098

spring.datasource.url=jdbc:postgresql://localhost:5432/authprac
spring.datasource.username=postgres
spring.datasource.password=Shakti
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update



spring.cloud.config.enabled=false

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

cloudinary.cloud-name=ds688jnk7
cloudinary.api-key=218583382113925
cloudinary.api-secret=58Tb1t7QkA7NFVZXYDmPfGlxvzA


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# rabbitmqctl delete_queue image.upload.queue
# rabbitmqctl declare_queue image.upload.queue true

