spring.application.name=demo


server.port=8098

spring.datasource.url=jdbc:postgresql://localhost:5432/authprac
spring.datasource.username=postgres
spring.datasource.password=Shakti
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update